export {move} from './board/action'
export {finishGame} from './board/action'
export {changePlayerState} from './board/action'
export {changeDifficulty} from './board/action'
export {changeTurn} from './board/action'
